### ISSUE TITLE
SyntaxError: Function statements require a function name

### ISSUE THREAD

**Issue by cjforzero** [Nihiue/little-byte#1]
您好，我想在electron使用little-byte,
但是会报错：
/Users/{userName}/Desktop/pro/vite-react-electron/dist/main/main.cjs.bytecode:1
 function (exports, require, module, __filename, __dirname) {                       
 ^^^^^^^^

SyntaxError: Function statements require a function name
    at new Script (node:vm:100:7)
    at loadBytecode (/Users/{userName}/Desktop/pro/vite-react-electron/node_modules/little-byte/lib/loader/index.js:21:20)
    at execByteCode (/Users/{userName}/Desktop/pro/vite-react-electron/node_modules/little-byte/lib/loader/index.js:32:20)
    at Object.loadModule [as .bytecode] (/Users/{userName}/Desktop/pro/vite-react-electron/node_modules/little-byte/lib/loader/index.js:37:23)
    at Module.load (node:internal/modules/cjs/loader:982:32)
    at Module._load (node:internal/modules/cjs/loader:823:12)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
    at Module.require (node:internal/modules/cjs/loader:1006:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    at Object.<anonymous> (/Users/{userName}/Desktop/pro/vite-react-electron/dist/main/index.cjs:18:1)

参考项目：
https://github.com/caoxiemeihao/vite-react-electron
在https://github.com/alexsnkr/vue-electron-bytenode中尝试将bytenode改成little-byte同样会报上述的错误

**Comment by hxkuc** [comment]
+1

**Comment by caoxiemeihao** [comment]
@Nihiue 华佗大佬，我也是碰到了这个问题。。。
<img width="1038" alt="image" src="https://user-images.githubusercontent.com/26263658/210314510-f9e5cd7e-8745-4ab6-98cd-e88474d16bf2.png">
<img width="777" alt="image" src="https://user-images.githubusercontent.com/26263658/210314532-670d98ce-dc04-4ba4-aece-d2d554a98d9a.png">

---

目前实现十分简单：
1. 首先将 `vite-plugin-electron` 生成的文件编译成对应的 `*.bytecode`
2. 然后将原来的文件变成一个加载 `*.bytecode` 代码段

```js
const { destname } = args // 上下文对象
const { name } = path.parse(destname!)
littleByte.compiler.compileFile(destname!)
const code = `require('little-byte').default.loader.execByteCode(require('path').join(__dirname, '${name}.bytecode'));`
fs.writeFileSync(destname!, code)
```

**Comment by caoxiemeihao** [comment]
代码仓库：https://github.com/electron-vite/vite-electron-plugin/tree/v0.8.0
实现文件：https://github.com/electron-vite/vite-electron-plugin/blob/v0.8.0/src-plugin/bytecode.ts
复现步骤：

```sh
1. pnpm i
2. cd examples/bytecode
3. npm run dev
```
